### ISSUE TITLE
"The provided token has expired" pops up a lot

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/aws-s3#182]
### Description

An error "The provided token has expired" pops up a lot randomly. 
I see that you guys tried to work around this already, but it doesn't seem to work: https://github.com/craftcms/aws-s3/blob/2.x/src/S3Client.php#L58-L65

### Steps to reproduce

1. I have no way to reproduce this consistenly, but my Sentry logger is catching these multiple times a day.

### Additional info

- Craft version: 5
- PHP version: 8.3
- Database driver & version: PostgreSQL
- Plugins & versions: S3

**Comment by boboldehampsink** [comment]
It should be fixed according to https://github.com/craftcms/aws-s3/commit/26a8bb6c79c0f4a973bec97b229fbc629029f1cb

But somehow I feel like it has regressed. Here is the error:

```
Client error: `PUT xxx` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message (truncated...)
 ExpiredToken (client): The provided token has expired. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0>XXX</Token-0><RequestId>XXX</RequestId><HostId>XXX</HostId></Error>
```

**Comment by angrybrad** [comment]
@boboldehampsink can you share a full stack trace from Sentry?

This is in a load-balanced environment, I assume?

**Comment by angrybrad** [comment]
Fixed in https://github.com/craftcms/aws-s3/releases/tag/2.2.2

**Comment by Romanavr** [comment]
> Fixed in https://github.com/craftcms/aws-s3/releases/tag/2.2.2

@angrybrad Could you re-open it? I'm still getting this error on 2.2.2.
Especially when I'm doing a lot of requests to S3 (=Saving new assets programatically in Craft)

Moreover, could you please check the following issue? Maybe it's related?
https://github.com/craftcms/aws-s3/issues/183

For context, I'm saving a lot of assets in a row.
And I see by the trace that the issue starts on: `Craft::$app->getElements()->saveElement($asset)`

```
League\Flysystem\UnableToWriteFile
Unable to write file at location: myfilename.jpg. Error executing "PutObject" on "https://s3.my-location-1.amazonaws.com/mybucketname/myfilename.jpg"; AWS HTTP error: Client error: `PUT https://s3.my-location-1.amazonaws.com/mybucketname/myfilename.jpg` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message (truncated...)
 ExpiredToken (client): The provided token has expired. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Token-0>*Token-Id*</RequestId><HostId>*Host-Id-Redacted*</HostId></Error>

```

**Comment by Jkhvatova** [comment]
I have the same issue as well.

**Comment by Romanavr** [comment]
@angrybrad Do you think this might be fixed in the coming days?

I've done some debugging and I think the problem is that the exception you use to re-generate the token is never called, as the problem occurs a bit later.
After configuring the S3 adapter.

I actually tried to reproduce this and did so with a small substitution (hardcoding) of the STS credentials to the expired token and along with the expired time, then cleared the data cache. I also added a `dd()` call to see if the S3 Exception would be triggered and didn't see it triggered (and not in trace log).
So here is the trace log I get with the expired token. Not sure if this helps or not.

```
2025-04-22 03:39:32 [console.ERROR] [craft\errors\FsException] GuzzleHttp\Exception\ClientException: Client error: `PUT https://s3.my-location-1.amazonaws.com/mybucketname-is/myfilename-is.jpg` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message (truncated...)
 in /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /app/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /app/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /app/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(167): GuzzleHttp\Promise\TaskQueue->run()
#5 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(206): GuzzleHttp\Handler\CurlMultiHandler->tick()
#6 /app/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#7 /app/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /app/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /app/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /app/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /app/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#12 /app/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#13 /app/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(35): GuzzleHttp\Promise\Promise->wait()
#14 /app/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(163): Aws\S3\S3Client->upload('mybucketname-is...', 'myfilename-is...', Resource id #2609, 'private', Array)
#15 /app/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(206): League\Flysystem\AwsS3V3\AwsS3V3Adapter->upload('myfilename-is...', Resource id #2609, Object(League\Flysystem\Config))
#16 /app/vendor/league/flysystem/src/Filesystem.php(67): League\Flysystem\AwsS3V3\AwsS3V3Adapter->writeStream('myfilename-is...', Resource id #2609, Object(League\Flysystem\Config))
#17 /app/vendor/craftcms/flysystem/src/base/FlysystemFs.php(137): League\Flysystem\Filesystem->writeStream('myfilename-is...', Resource id #2609, Array)
#18 /app/vendor/craftcms/cms/src/models/Volume.php(631): craft\flysystem\base\FlysystemFs->writeFileFromStream('myfilename-is...', Resource id #2609, Array)
#19 /app/vendor/craftcms/cms/src/elements/Asset.php(3571): craft\models\Volume->writeFileFromStream('myfilename-is...', Resource id #2609, Array)
#20 /app/vendor/craftcms/cms/src/elements/Asset.php(3258): craft\elements\Asset->_relocateFile()
#21 /app/vendor/craftcms/cms/src/services/Elements.php(3943): craft\elements\Asset->afterSave(true)
#22 /app/vendor/craftcms/cms/src/services/Elements.php(1251): craft\services\Elements->craft\services\{closure}()
#23 /app/vendor/craftcms/cms/src/services/Elements.php(3742): craft\services\Elements->ensureBulkOp(Object(Closure))
#24 /app/vendor/craftcms/cms/src/services/Elements.php(1337): craft\services\Elements->_saveElementInternal(Object(craft\elements\Asset), true, true, NULL, Array, false, false, false)
*My service to save new Asset element called before*
```

**Comment by boboldehampsink** [comment]
@angrybrad any news on this?

**Comment by white-rick** [comment]
We also got this error when running `craft index-assets/one assets`.

```
Error executing "ListObjectsV2" on "https://s3.eu-central-1.amazonaws.com/xxx?list-type=2&prefix=assets%2F&continuation-token=..."; AWS HTTP error: Client error: `GET https://s3.eu-central-1.amazonaws.com/xxx?list-type=2&prefix=assets%2F&continuation-token=...` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message (truncated...)
 ExpiredToken (client): The provided token has expired. - <?xml version="1.0" encoding="UTF-8"?>
 ```

And we also save assets programmatically where we do get a lot of these errors . I'm not sure if it's exact the same issue, but is looks related.

`craft\errors\FsException: Unable to check if productimages/test.pdf exists`

```
/var/www/html/vendor/craftcms/cms/src/models/Volume.php(433): craft\flysystem\base\FlysystemFs->fileExists('productimages/t...')
#1 /var/www/html/vendor/craftcms/cms/src/services/Assets.php(814): craft\models\Volume->fileExists('productimages/t...')
#2 /var/www/html/vendor/craftcms/cms/src/services/Assets.php(817): craft\services\Assets::craft\services\{closure}('test.pdf')
#3 /var/www/html/vendor/craftcms/cms/src/validators/AssetLocationValidator.php(125): craft\services\Assets->getNameReplacementInFolder('test.pdf', 9)
#4 /var/www/html/vendor/yiisoft/yii2/validators/Validator.php(260): craft\validators\AssetLocationValidator->validateAttribute(Object(craft\elements\Asset), 'newLocation')
#5 /var/www/html/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(craft\elements\Asset), Array)
#6 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2505): yii\base\Model->validate(Array, true)
#7 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(3307): craft\base\Element->validate(NULL)
#8 /var/www/html/vendor/craftcms/cms/src/services/Elements.php(1108): craft\services\Elements->_saveElementInternal(Object(craft\elements\Asset), true, true, NULL, Array, false, false)
#9 /var/www/html/vendor/white-dev/privateplugin/src/services/Assets.php(92): craft\services\Elements->saveElement(Object(craft\elements\Asset))
```
Inner exception:
```
Aws\S3\Exception\S3Exception: Error executing "HeadObject" on "https://s3.eu-central-1.amazonaws.com/xxx/assets/productimages/test.pdf"; AWS HTTP error: Client error: `HEAD https://s3.eu-central-1.amazonaws.com/xxx/assets/productimages/test.pdf` resulted in a `400 Bad Request` response (client): 400 Bad Request
```

Any idea on this one?

**Comment by michtio** [comment]
@angrybrad issue still persists. Token has expired is the main issue on this, the funny part is for me personally it always happens after `999` assets have been indexed. Always the same number!

I can fix this by running in batches of e.g. 998 based on the id's, but that's quite labor intensive to follow-up.

**Comment by angrybrad** [comment]
To set expectations, it’s going to be a while before I can look back into this. Particularly swamped at the moment.

If someone has found a way to reliably reproduce this in a test case and can share the files/steps to support@craftcms.com, that would greatly help.

**Comment by michtio** [comment]
@angrybrad I'll keep an eye on it, I think it's quite intermittent (and might be hard to hunt down) as sometimes it happens, sometimes it doesn't.

Whenever I can pinpoint it I'll shoot over a detailed description.

**Comment by epapada** [comment]
Same problem here - trying to index 90.000 files - it fails around 40000 (exactly one hour - so the tokens seems to last for an hour) - anyone found a workaround?

**Comment by white-mark-w** [comment]
Still no progress on this issue? Indexing assets in a large volume is impossible because of this issue.

**Comment by angrybrad** [comment]
Just released https://github.com/craftcms/aws-s3/releases/tag/2.3.0 with another attempt at fixing this (thanks @boboldehampsink)!
